### ISSUE TITLE
Metadata fields should be inherited from a more generic base class

### ISSUE THREAD

**Issue by cmungall** [geneontology/GO_Shapes#4]
e.g.

```
<BP> {
  a . *;
  contributor: . *;
  date: . *;
  providedBy: . *;
  xref: . *;
  rdfs:label . *;
  exactMatch: . *;
  rdfs:comment: . *;
  bl:category [biological_process:]  ;
  part_of: @<BP> *;
} // rdfs:comment  "A biological process"
```

Most of these can be inherited from an Entity base shape.

label should be {0,1} ("normal" entities don't have individual-level labels, but these are useful for reactome. But they should never have >1)

Not sure why xref and exactMatch are in there?

**Comment by goodb** [comment]
1. Why not allow for the possibility of more than one label?  What breaks if there is another one?
2. exactMatch is in there because it is used to match up go-cam uris to the uris in the biobpax they were generated from. 
3. xref is in there because that is how obo world seems to want to handle lining up equivalent database entities.  

All of the above are aspects of the export process.  This process could be changed, though to me, they all seem like fairly reasonable things to include in an RDF data store.
